project_structure:
    contracts: contracts

compiler:
    solc:
#        version: 0.8.4
        optimizer:
            enabled: false
#            runs: 200
        remappings:
            - "@openzeppelin=/home/v/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0"
            - "@openzeppelin/contracts-upgradeable=/home/v/.brownie/packages/OpenZeppelin/openzeppelin-contracts-upgradeable@3.3.0/contracts"
            - "@openzeppelin@4.1.0=/home/v/.brownie/packages/OpenZeppelin/openzeppelin-contracts@4.1.0"

#            - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@3.1.0/contracts"
#            - "@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@3.3.0/contracts"
#            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0"
#            - "@openzeppelin@4.1.0=OpenZeppelin/openzeppelin-contracts@4.1.0"
##            - "@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@3.3.0"
##            - "@openzeppelin-upgradeable@4.1.0=OpenZeppelin/openzeppelin-contracts-upgradeable@4.1.0"

dependencies:
    - brownie-mix/token-mix@1.0.0
    - OpenZeppelin/openzeppelin-contracts@3.1.0
    - OpenZeppelin/openzeppelin-contracts@4.1.0
    - OpenZeppelin/openzeppelin-contracts-upgradeable@4.1.0
    - OpenZeppelin/openzeppelin-contracts-upgradeable@3.3.0
